/* No build step, external fonts, UI frameworks, or CDN dependencies. */
'use strict';
const C=Lab,$=s=>document.querySelector(s), money=x=>x==null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(x),pct=x=>x==null?'—':`${x>=0?'+':''}${(x*100).toFixed(1)}%`, h=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={INFY:'Infosys',RELIANCE:'Reliance Industries',TCS:'Tata Consultancy Services',HDFCBANK:'HDFC Bank',ICICIBANK:'ICICI Bank',LT:'Larsen & Toubro',ITC:'ITC',SUNPHARMA:'Sun Pharmaceutical',NIFTYBEES:'Nifty BeES ETF'};
const DEFAULT_WATCH=['INFY','RELIANCE','TCS','HDFCBANK','ICICIBANK','LT','ITC','SUNPHARMA'];
const TITLES={learning:'Prediction history',overview:'Overview',research:'Stock research',backtest:'Strategy lab',portfolio:'My portfolio',data:'Data & settings'};
let mode='real',page='overview',selected='INFY',watch=[...DEFAULT_WATCH],bps=20,period=252,filter='all',busy=false,marketErrors=[],dataCache={},db=null,cacheError='',settingsError='',renderCount=0;
let researchMemo=new Map();const demoCache={};
const storeKey=(suffix)=>`niftylab-v2-${mode}-${suffix}`;
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),6000);}
function read(suffix,fallback){const raw=localStorage.getItem(storeKey(suffix));return raw===null?fallback:JSON.parse(raw);}
function write(suffix,value){localStorage.setItem(storeKey(suffix),JSON.stringify(value));}
function uid(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;}
function seed(){if(localStorage.getItem('niftylab-v2-demo-ledger')!==null)return;const a=C.demo('INFY'),b=C.demo('ICICIBANK');localStorage.setItem('niftylab-v2-demo-ledger',JSON.stringify([
{id:'demo-deposit',date:a.at(-150).date,kind:'DEPOSIT',symbol:'',quantity:0,price:250000,fees:0},
{id:'demo-infy',date:a.at(-120).date,kind:'BUY',symbol:'INFY',quantity:20,price:Number(a.at(-120).rawClose.toFixed(2)),fees:35},
{id:'demo-icici',date:b.at(-80).date,kind:'BUY',symbol:'ICICIBANK',quantity:30,price:Number(b.at(-80).rawClose.toFixed(2)),fees:25}
]));}
function dataset(s){if(mode==='demo'){if(!demoCache[s])demoCache[s]={bars:C.demo(s),source:'Synthetic demo',symbol:s};return demoCache[s];}return dataCache[s];}
function analyze(s){const key=mode+':'+s;if(researchMemo.has(key))return researchMemo.get(key);const a=dataset(s),b=dataset('NIFTYBEES');if(!a||!b)return null;try{const result=C.features(a.bars,b.bars);researchMemo.set(key,result);return result;}catch{return null;}}
function positionBook(){return C.ledger(read('ledger',[]));}
function portfolioState(){const book=positionBook(),marks={},missing=[],dates={};for(const s of Object.keys(book.holdings)){const d=dataset(s);if(!d||(mode==='real'&&C.stale(d.bars))){missing.push(s);continue;}marks[s]=d.bars.at(-1).rawClose;dates[s]=d.bars.at(-1).date;}return {book,marks,missing,dates,value:missing.length?null:C.valuation(book,marks)};}
function stateBadge(d){if(!d)return '<span class="pill neutral">NO DATA</span>';if(mode==='real'&&C.stale(d))return '<span class="pill wait">STALE</span>';return d.at(-1).signal?'<span class="pill">● CANDIDATE</span>':'<span class="pill wait">WAIT</span>';}
function kpi(label,value,note='',dark=false){return `<div class="kpi ${dark?'dark':''}"><label>${h(label)}</label><div class="kpi-value">${value}</div><div class="kpi-note">${note}</div></div>`;}
function heading(eyebrow,title,subtitle,actions=''){return `<div class="page-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="subtitle">${subtitle}</p></div><div class="actions">${actions}</div></div>`;}
function stockSelect(){return `<label class="sr-only" for="stock-selector">Research symbol</label><select id="stock-selector">${[...new Set([...watch,selected])].map(s=>`<option ${s===selected?'selected':''}>${h(s)}</option>`).join('')}</select>`;}
function refreshButton(){return `<button class="${mode==='real'?'primary':'subtle'}" data-action="refresh" ${busy?'disabled':''}>${busy?'Fetching history…':mode==='demo'?'↻ Refresh view':'↻ Fetch market data'}</button>`;}
function noData(){return `<div class="empty"><h3>Bring your market data into view</h3><p>Fetch daily history with the optional local server, or import stock and NIFTYBEES price CSVs in Data & settings. We never replace a failed market request with demo prices.</p><div class="actions" style="justify-content:center">${refreshButton()}<button data-page="data">Import CSVs</button></div></div>`;}
function errorList(){return mode==='real'&&marketErrors.length?`<details class="callout error" open><summary>Some market data could not be loaded</summary>${marketErrors.map(e=>`<p>${h(e)}</p>`).join('')}</details>`:'';}
function chart(points,keys,labels,id='main-chart'){
 if(points.length<2)return '<p class="muted">Not enough history to chart.</p>';
 const w=window.innerWidth<600?360:780,hei=267,pad={l:46,r:12,t:13,b:30},values=points.flatMap(p=>keys.map(k=>p[k]).filter(Number.isFinite));let lo=Math.min(...values),hi=Math.max(...values);if(hi===lo){hi+=1;lo-=1;}const span=hi-lo;lo-=span*.12;hi+=span*.12;
 const x=i=>pad.l+i/(points.length-1)*(w-pad.l-pad.r),y=v=>pad.t+(hi-v)/(hi-lo)*(hei-pad.t-pad.b);
 let svg='';for(let i=0;i<5;i++){const val=lo+(hi-lo)*i/4,yy=y(val);svg+=`<line x1="${pad.l}" x2="${w-pad.r}" y1="${yy}" y2="${yy}" stroke="#edf0e8"/><text x="${pad.l-10}" y="${yy+3}" text-anchor="end">${val.toFixed(0)}</text>`;}
 keys.forEach((key,j)=>{let path='';points.forEach((p,i)=>{if(Number.isFinite(p[key]))path+=`${path?'L':'M'}${x(i).toFixed(2)},${y(p[key]).toFixed(2)} `;});if(j===0){svg+=`<path d="${path}L${x(points.length-1)},${hei-pad.b} L${pad.l},${hei-pad.b}Z" fill="url(#${id}-fill)"/>`;}svg+=`<path d="${path}" fill="none" stroke="${j?'#c0ad80':'#277454'}" stroke-width="${j?1.8:2.3}" ${j?'stroke-dasharray="5 4"':''} stroke-linecap="round" stroke-linejoin="round"/>`;});
 [0,Math.floor(points.length/3),Math.floor(2*points.length/3),points.length-1].forEach((i,j)=>svg+=`<text x="${x(i)}" y="${hei-6}" text-anchor="${j===0?'start':j===3?'end':'middle'}">${h(points[i].date.slice(0,7))}</text>`);
 charts[id]={points,keys,labels,width:w};
 return `<div class="legend">${labels.map(l=>`<span>${h(l)}</span>`).join('')}</div><div class="chart" data-chart="${id}"><svg viewBox="0 0 ${w} ${hei}" role="img" aria-label="${h(labels.join(' versus '))} from ${points[0].date} to ${points.at(-1).date}"><defs><linearGradient id="${id}-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#2d7855" stop-opacity=".10"/><stop offset="100%" stop-color="#2d7855" stop-opacity="0"/></linearGradient></defs>${svg}</svg><div class="chart-tooltip" hidden></div></div>`;
}
let charts={};
function watchTable(){const rows=watch.map(s=>({s,d:analyze(s)})).sort((a,b)=>(b.d?.at(-1).score??-1)-(a.d?.at(-1).score??-1));const shown=rows.filter(({d})=>filter!=='candidate'||(d?.at(-1).signal&&!(mode==='real'&&C.stale(d))));
return `<div class="panel"><div class="section-top table-top"><div><h2>Your watchlist</h2><p>A research universe you control. ${watch.length} symbols.</p></div><div class="filter-row"><label class="sr-only" for="watch-filter">Filter watchlist</label><select id="watch-filter"><option value="all" ${filter==='all'?'selected':''}>All stocks</option><option value="candidate" ${filter==='candidate'?'selected':''}>Candidates only</option></select><button class="link-button" data-page="data">Edit watchlist ↗</button></div></div><div class="table-wrap"><table><thead><tr><th>Company</th><th>Last close</th><th>63-session return</th><th>Rule score</th><th>Status</th><th>Research</th></tr></thead><tbody>${shown.map(({s,d})=>{const b=dataset(s)?.bars.at(-1),last=d?.at(-1);return `<tr><td><div class="ticker-name"><span class="symbol-tile">${h(s.slice(0,2))}</span><div><b>${h(s)}</b><div class="name-detail">${h(names[s]||'NSE-listed instrument')}</div></div></div></td><td>${money(b?.rawClose)}<div class="name-detail">${h(b?.date||'No data')}</div></td><td class="${last?.momentum>=0?'positive':'negative'}">${pct(last?.momentum)}</td><td><div class="score-cell"><div class="score-track"><span style="width:${last?.score||0}%"></span></div>${last?last.score+'/100':'—'}</div></td><td>${stateBadge(d)}</td><td><button class="small" data-stock="${h(s)}" aria-label="Research ${h(s)}">Open ↗</button></td></tr>`;}).join('')||'<tr><td colspan="6">No stocks satisfy this filter.</td></tr>'}</tbody></table></div><p class="panel-note">Rule score counts passing conditions. It is not a probability of profit or a maintained list of Nifty constituents.</p></div>`;
}
function overview(){const p=portfolioState(),available=watch.map(s=>analyze(s)).filter(Boolean),candidates=available.filter(d=>d.at(-1).signal&&!(mode==='real'&&C.stale(d))).length,d=analyze(selected),last=d?.at(-1);
const points=d?.slice(-period).map((b,i,arr)=>({date:b.date,stock:100*b.close/arr[0].close,benchmark:100*b.bench/arr[0].bench}))||[];
return heading('YOUR DAILY PERSPECTIVE','Invest with a thesis.','Understand what you own. Know what deserves a closer look.',`<button data-action="transaction">+ Add transaction</button>${refreshButton()}`)+
`<div class="kpis">${kpi('Portfolio value',money(p.value?.equity),'Cash + marked holdings',true)}${kpi('Total profit',`<span class="${p.value?.profit>=0?'positive':'negative'}">${money(p.value?.profit)}</span>`,'Since recorded deposits · includes dividends')}${kpi('Available cash',money(p.book.cash),'Ready to allocate, when the evidence fits')}${kpi('Research candidates',`${candidates}<span style="font-size:14px;color:#9aa494"> / ${watch.length}</span>`,`${available.length} symbols have sufficient history`)}</div>`+
(p.missing.length?`<div class="callout error">Portfolio total is withheld: recent marks are missing for ${h(p.missing.join(', '))}.</div>`:'')+errorList()+
`<div class="two-col"><section class="panel"><div class="section-top"><div><h2>Performance in perspective</h2><p>Growth of 100 · selected stock vs Nifty ETF</p></div><div class="filter-row">${stockSelect()}<label class="sr-only" for="period">Chart period</label><select id="period"><option value="126" ${period===126?'selected':''}>6M</option><option value="252" ${period===252?'selected':''}>1Y</option><option value="504" ${period===504?'selected':''}>2Y</option></select></div></div>${d?chart(points,['stock','benchmark'],[selected,'NIFTYBEES']):noData()}<p class="panel-note">${mode==='demo'?'Illustrative synthetic history.':`Adjusted prices · ${h(d?.at(-1).date||'awaiting data')}.`} This is a stock comparison, not your portfolio return.</p></section>
<section class="panel"><div class="section-top"><h2>The case for ${h(selected)}</h2>${stateBadge(d)}</div>${d?`<p class="text-body">${last.signal?'All five baseline conditions align. Examine the risks before considering an allocation.':'The baseline is not fully aligned. Waiting is a valid decision.'}</p>${last.rules.map((pass,i)=>`<div class="rule-line"><span class="rule-dot ${pass?'':'fail'}">${pass?'✓':'–'}</span>${C.RULES[i]}</div>`).join('')}<div class="callout">${last.signal?'Next question: does it fit your portfolio?':'Missing evidence matters as much as passing signals.'}</div><button class="link-button" data-stock="${h(selected)}">Read the full investment case ↗</button>`:noData()}</section></div>${watchTable()}`;
}
function sizingPanel(s,d){const p=portfolioState(),b=d.at(-1),price=b.rawClose,stop=Math.max(price*.01,price-Math.max(2*b.atr*price/b.close,price*.05));
return `<section class="panel"><div class="section-top"><div><h2>Plan the allocation</h2><p>Additional shares · based on your ledger</p></div></div><form id="size-form"><div class="form-grid"><label>Loss budget (% of equity)<input name="risk" type="number" min="0.1" max="5" step="0.1" value="0.5" required></label><label>Total position cap (%)<input name="cap" type="number" min="1" max="100" value="10" required></label><label class="full">Hypothetical exit level (₹)<input name="stop" type="number" min="0.01" step="0.01" value="${stop.toFixed(2)}" required></label></div><p class="form-help">Default exit: the wider of 2×ATR or 5% below the latest close. This is a risk scenario, not an optimized stop.</p><button class="primary" type="submit">Calculate position ↗</button></form><div id="size-result"></div><p class="panel-note">Cash available: ${money(p.book.cash)}. Fees use the strategy lab setting (${bps} bps/side). Price gaps can exceed planned loss. Sector correlation and total portfolio stop risk are not modeled.</p></section>`;
}
function research(){const d=analyze(selected);let html=heading('FROM SIGNAL TO DECISION',h(names[selected]||selected),`NSE: ${h(selected)} · daily, long-only research`,stockSelect()+refreshButton());if(!d)return html+errorList()+noData();const b=d.at(-1),e=C.evidence(d,21,bps),note=read('notes',{})[selected]||'';
html+=`<div class="kpis">${kpi('Latest close',money(b.rawClose),h(b.date),true)}${kpi('Baseline conditions',`${b.score/20} / 5`,stateBadge(d))}${kpi('Historical positive outcomes',e.rate===null?'—':(e.rate*100).toFixed(0)+'%',`${e.n} non-overlapping 21-session samples`)}${kpi('Descriptive 95% interval',e.interval?`${(e.interval[0]*100).toFixed(0)}–${(e.interval[1]*100).toFixed(0)}%`:'Unavailable','Not a calibrated prediction')}</div>`;
html+=`<div class="two-col"><div><section class="panel"><div class="section-top"><h2>The evidence, condition by condition</h2>${stateBadge(d)}</div>${b.rules.map((pass,i)=>`<div class="list-row"><div class="rule-line" style="margin:0"><span class="rule-dot ${pass?'':'fail'}">${pass?'✓':'–'}</span><div>${C.RULES[i]}<small>${h([`Adjusted close ${b.close.toFixed(2)} · MA200 ${b.ma200.toFixed(2)}`,`MA50 ${b.ma50.toFixed(2)} · MA200 ${b.ma200.toFixed(2)}`,`Trailing 63-session return ${pct(b.momentum)}`,`Excess over NIFTYBEES ${pct(b.relative)}`,'A broad-market trend filter, not a macroeconomic forecast.'][i])}</small></div></div><span class="pill ${pass?'':'wait'}">${pass?'PASS':'FAIL'}</span></div>`).join('')}<div class="callout">${b.signal?'The baseline flags a research candidate. It has not established an investing advantage.':'Suggested additional purchase under this baseline: 0 shares until all conditions align.'}</div></section>
<section class="panel stack"><h2>The counterargument</h2><p class="text-body" style="margin-top:13px">Price trends do not tell us whether this business is fairly valued. Earnings, governance, liquidity shocks and sudden news can overwhelm every passing condition. This model has no fundamental or news inputs.</p><form id="journal-form"><label class="journal-label">Your thesis & what would invalidate it<textarea name="note" class="journal" maxlength="5000" placeholder="Why this business? What would change your mind?">${h(note)}</textarea></label><div class="button-row"><button type="submit" class="small">Save research note</button></div></form></section>
<section class="panel stack"><h2>Inspect the historical evidence</h2><p class="text-body" style="margin-top:10px">Decision at the close, entry at the next open, exit 21 sessions later. Samples never overlap and must be fully matured. ${bps} bps is charged on each side.</p>${e.n<30?'<div class="callout">Fewer than 30 observations: the historical sample is small.</div>':''}<p class="panel-note">The Wilson interval describes historical positive-return frequency. Market observations are not independent; uncertainty can be understated. The fixed-horizon exits here differ from the strategy lab’s signal-based exits.</p><details><summary>View ${e.n} individual outcomes</summary>${evidenceTable(e.samples)}</details></section></div><div>${sizingPanel(selected,d)}<section class="panel stack"><h2>Keep the benchmark honest</h2><p class="text-body" style="margin-top:13px">NIFTYBEES is an investable Nifty ETF proxy, not the official total-return index. We compare on matching dates using adjusted history. Selecting a successful stock after the fact can make any strategy look better.</p><div class="button-row"><button data-page="backtest">Test the strategy →</button></div></section></div></div>`;return html;
}
function evidenceTable(samples){return `<div class="table-wrap"><table><thead><tr><th>Decision</th><th>Entry</th><th>Exit</th><th>Net return</th><th>Excess vs ETF</th></tr></thead><tbody>${samples.map(s=>`<tr><td>${s.decision}</td><td>${s.entry}</td><td>${s.exit}</td><td class="${s.return>=0?'positive':'negative'}">${pct(s.return)}</td><td>${pct(s.excess)}</td></tr>`).join('')||'<tr><td colspan="5">No matured eligible observations.</td></tr>'}</tbody></table></div>`;}
function backtestPage(){const d=analyze(selected);let html=heading('TEST BEFORE YOU TRUST','Strategy lab','A fixed-rule baseline. Every entry follows a completed signal.',stockSelect()+refreshButton());if(!d)return html+errorList()+noData();
let start=read('backtest-start',null)||d[Math.max(200,d.length-504)].date;if(start<d[200].date||start>d.at(-31).date)start=d[Math.max(200,d.length-504)].date;
const result=C.backtest(d,start,bps),points=result.points.map(p=>({...p,strategy:p.strategy*100,benchmark:p.benchmark*100}));
return html+`<section class="panel" style="margin-bottom:20px"><form id="backtest-form" class="inline-form"><label>Evaluation start<input type="date" name="start" value="${start}" min="${d[200].date}" max="${d.at(-31).date}" required></label><label>One-way costs (bps)<input class="cost-control" name="bps" type="number" min="0" max="1000" step="1" value="${bps}" required></label><button class="primary" type="submit">Run evaluation ↗</button><button type="button" data-action="export-backtest">↓ Export curve</button></form></section><div class="kpis">${kpi('Strategy total return',pct(result.strategy.total),'After estimated trading costs',true)}${kpi('Nifty ETF total return',pct(result.benchmark.total),'Matching entry date and endpoint')}${kpi('Strategy max drawdown',pct(result.strategy.drawdown),'Worst peak-to-trough decline')}${kpi('Time invested',(result.exposure*100).toFixed(0)+'%',`${result.orders} buy / sell executions`)}</div><div class="two-col"><section class="panel"><div class="section-top"><div><h2>Growth of 100</h2><p>${start} to ${d.at(-1).date} · ${bps} bps per side</p></div><span class="pill neutral">${mode==='demo'?'SYNTHETIC':'HISTORICAL'} EVALUATION</span></div>${chart(points,['strategy','benchmark'],[selected+' strategy','NIFTYBEES'],'backtest-chart')}<div class="table-wrap"><table><thead><tr><th>Series</th><th>Total return</th><th>CAGR</th><th>Max drawdown</th></tr></thead><tbody>${[['Strategy',result.strategy],['Nifty ETF',result.benchmark]].map(([n,s])=>`<tr><td>${n}</td><td>${pct(s.total)}</td><td>${pct(s.cagr)}</td><td>${pct(s.drawdown)}</td></tr>`).join('')}</tbody></table></div></section><section class="panel"><h2>What this test actually does</h2><div class="text-body" style="margin-top:15px"><p><b>Entry:</b> all five rules pass at a close; buy at the next session’s open.</p><p><b>Exit:</b> any rule fails; sell at the next session’s open.</p><p><b>Allocation:</b> 100% in the selected stock or cash, with fractional units. This is distinct from your position calculator.</p><p><b>Costs:</b> estimated fees and slippage per side, plus endpoint liquidation. Taxes are excluded.</p><p><b>Limitations:</b> no point-in-time fundamentals, no historical index membership, no calibration or untouched model-training holdout. Repeated date and stock selection biases the result.</p></div></section></div><section class="panel"><h2>Cost sensitivity</h2><p class="panel-note">A useful result should survive plausible friction. Cost settings below are scenarios, not current brokerage tariffs.</p><div class="table-wrap"><table><thead><tr><th>Cost per side</th><th>Strategy return</th><th>Nifty ETF return</th><th>Strategy drawdown</th></tr></thead><tbody>${[0,20,50,100].map(c=>{const r=C.backtest(d,start,c);return `<tr><td>${c} bps</td><td>${pct(r.strategy.total)}</td><td>${pct(r.benchmark.total)}</td><td>${pct(r.strategy.drawdown)}</td></tr>`;}).join('')}</tbody></table></div></section>`;
}
function ledgerPortfolioPage(){const p=portfolioState(),rows=read('ledger',[]),snaps=read('snapshots',[]),colors=['#327356','#88a080','#b5b895','#d2c69e','#a6bcb4'];
let html=heading('YOUR CAPITAL, ACCOUNTED FOR','My portfolio','Original purchases, partial sales, cash and profit. All in one place.',`<button data-action="export-ledger">↓ Backup</button><button class="primary" data-action="transaction">+ Add transaction</button>`);
html+=`<div class="kpis">${kpi('Marked equity',money(p.value?.equity),'Cash + holdings · latest available closes',true)}${kpi('Unrealized P&L',money(p.value?.unrealized),'Against remaining FIFO cost basis')}${kpi('Realized trading P&L',money(p.book.realized),'After recorded buy and sell fees')}${kpi('Available cash',money(p.book.cash),`Dividends received: ${money(p.book.dividends)}`)}</div>`;
if(p.missing.length)html+=`<div class="callout error">Totals withheld until all holdings have recent prices: ${h(p.missing.join(', '))}. ${refreshButton()}</div>`;
html+=`<section class="panel"><div class="section-top"><div><h2>Open positions</h2><p>Trade amounts are rounded to paise. Corporate actions are entered manually.</p></div><button class="link-button" data-action="refresh">Refresh prices ↻</button></div><div class="table-wrap"><table><thead><tr><th>Holding</th><th>Shares</th><th>Avg. cost</th><th>Last close</th><th>Market value</th><th>Unrealized P&L</th><th>Price date</th></tr></thead><tbody>${Object.entries(p.book.holdings).map(([s,b])=>{const mark=p.marks[s],value=mark==null?null:mark*b.quantity,pnl=value==null?null:value-b.basis;return `<tr><td><button class="link-button" data-stock="${h(s)}">${h(s)}</button><div class="name-detail">Oldest lot ${h(b.first)}</div></td><td>${b.quantity.toLocaleString('en-IN',{maximumFractionDigits:6})}</td><td>${money(b.average)}</td><td>${money(mark)}</td><td>${money(value)}</td><td class="${pnl>=0?'positive':'negative'}">${money(pnl)}</td><td>${h(p.dates[s]||'Unavailable')}</td></tr>`;}).join('')||'<tr><td colspan="7">No positions yet. Add your funding deposit, then your original dated purchases.</td></tr>'}</tbody></table></div></section>`;
html+=`<div class="two-col" style="margin-top:20px"><section class="panel"><div class="section-top"><div><h2>Profit over time</h2><p>Saved observations · deposits excluded from profit</p></div><button class="small" data-action="snapshot" ${p.value?'':'disabled'}>+ Save snapshot</button></div>${snaps.length>1?chart(snaps.map(s=>({date:s.date,profit:s.profit})),['profit'],['Total P&L'],'portfolio-chart'):'<div class="empty"><h3>Start a progress record</h3><p>Save a snapshot when you review your portfolio. Two observations unlock this chart. It is not a reconstructed or time-weighted return series.</p></div>'}<p class="panel-note">Snapshot date is the review date; values use the price dates above. Backdated ledger changes invalidate affected snapshots.</p></section><section class="panel"><h2>Where your capital sits</h2>${p.value&&p.value.equity>0?`<div class="allocation-bar">${[...Object.entries(p.book.holdings).map(([s,b])=>[s,b.quantity*p.marks[s]]),['Cash',p.book.cash]].map(([s,v],i)=>`<span title="${h(s)} ${(100*v/p.value.equity).toFixed(1)}%" style="width:${100*v/p.value.equity}%;background:${colors[i%colors.length]}"></span>`).join('')}</div>${[...Object.entries(p.book.holdings).map(([s,b])=>[s,b.quantity*p.marks[s]]),['Cash',p.book.cash]].map(([s,v])=>`<div class="list-row"><span>${h(s)}</span><b>${(100*v/p.value.equity).toFixed(1)}%</b></div>`).join('')}`:'<p class="text-body" style="margin-top:15px">Fund your ledger and load all holding prices to see the allocation.</p>'}<p class="panel-note">Total profit: ${money(p.value?.profit)} · Net deposits: ${money(p.book.net)}. Excludes future sale costs and taxes.</p></section></div>`;
html+=`<section class="panel"><div class="section-top"><div><h2>Transaction ledger</h2><p>Same-day transactions follow their insertion order.</p></div><button class="small" data-action="export-ledger">Export JSON</button></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Symbol</th><th>Quantity / ratio</th><th>Price / amount</th><th>Fees</th><th>Correct</th></tr></thead><tbody>${[...rows].map((r,i)=>({...r,index:i})).sort((a,b)=>b.date.localeCompare(a.date)||b.index-a.index).map(r=>`<tr><td>${h(r.date)}</td><td><span class="pill neutral">${h(r.kind)}</span></td><td>${h(r.symbol||'—')}</td><td>${h(r.quantity||'—')}</td><td>${money(r.price)}</td><td>${money(r.fees)}</td><td><button class="small" data-delete="${h(r.id)}" aria-label="Delete ${h(r.kind)} on ${h(r.date)}">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">Your real portfolio starts empty.</td></tr>'}</tbody></table></div><p class="panel-note">Deleting a funding deposit or purchase is blocked when it would invalidate later transactions. To correct an entry, delete it and add the corrected trade.</p></section>`;return html;
}
function dataPage(){return heading('MAKE THE WORKSPACE YOURS','Data & settings','Import history, manage your watchlist and keep a portable backup.')+`${cacheError?`<div class="callout error">${h(cacheError)}</div>`:''}<div class="help-grid"><section class="panel"><h2>Your research universe</h2><form id="watch-form"><label style="margin-top:16px">NSE symbols, separated by commas<textarea name="symbols" class="journal watch-input" maxlength="800">${h(watch.join(', '))}</textarea></label><p class="form-help">Up to 20 instruments. This list is editable, not an automatically updated Nifty constituent list.</p><button class="primary" type="submit">Save watchlist</button></form></section><section class="panel"><h2>Real daily market history</h2><p class="text-body" style="margin-top:13px">To enable fetching, run <code>python3 server.py</code> in the project folder and open <code>http://127.0.0.1:8765</code>. No Python packages are required. On Windows use <code>py server.py</code>.</p><div class="callout">Source: Yahoo Finance, an unofficial personal-research feed. It can be delayed, blocked or rate-limited. Completed candles train the model; separate indicative quotes value holdings during the session.</div>${refreshButton()}</section>
<section class="panel"><h2>Import a price CSV</h2><p class="text-body" style="margin:12px 0">Required columns: <code>Date,Open,High,Low,Close,Adj Close,Volume</code>. Import <b>NIFTYBEES</b> too; research requires at least 260 matching sessions.</p><form id="price-import"><div class="form-grid"><label>Instrument<input name="symbol" value="${h(selected)}" required maxlength="30"></label><label>CSV file<input name="file" type="file" accept=".csv,text/csv" required></label></div><p class="form-help">Adj Close must be consistently adjusted for distributions. Raw Close is retained for valuing current holdings. Dates must be unique and earlier than today.</p><button class="primary" ${mode==='demo'?'disabled':''}>Import into real workspace</button></form><div class="button-row"><button class="small" data-action="price-template">↓ Price CSV example</button></div>${mode==='demo'?'<p class="panel-note">Switch to My real portfolio before importing real data.</p>':''}</section>
<section class="panel"><h2>Portfolio backup & migration</h2><p class="text-body" style="margin:12px 0">Export before moving devices, clearing browser data or changing the address used to open this app. File-open and localhost workspaces have separate browser storage.</p><div class="button-row"><button data-action="export-ledger">↓ Export full backup</button></div><form id="ledger-import" style="margin-top:17px"><label>JSON backup or old Streamlit export<input name="file" type="file" accept=".json,application/json" required></label><div class="button-row"><button type="submit">Validate & preview import</button></div></form><div id="restore-preview"></div><p class="panel-note">Recognizes old DEPOSIT / WITHDRAW / BUY / SELL / DIVIDEND / SPLIT exports. Reviews the whole ledger before saving. Snapshots and notes are included in new backups.</p></section>
<section class="panel"><h2>Available real datasets</h2>${Object.entries(dataCache).map(([s,d])=>`<div class="data-card"><b>${h(s)}</b> <span class="pill neutral">${d.bars.length} BARS</span><br><small>${h(d.source)} · ${d.bars[0].date} → ${d.bars.at(-1).date}</small><div class="button-row"><button class="small" data-export-price="${h(s)}">Export CSV</button></div></div>`).join('')||'<p class="text-body" style="margin-top:12px">No real datasets loaded. Fetch history or import CSVs.</p>'}</section>
<section class="panel"><h2>What the model can—and cannot—say</h2><div class="text-body" style="margin-top:13px"><p><b>Rule score:</b> 20 points per passing condition. This is not predictive confidence.</p><p><b>Historical evidence:</b> non-overlapping 21-session outcomes and a descriptive Wilson interval. Dependence between market regimes can understate uncertainty.</p><p><b>Research baseline:</b> no claim of market-beating returns. Fundamentals, news, historical constituents, sector risk and predictive calibration are future work.</p><p><b>Portfolio:</b> FIFO accounting with paise rounding. Dividends and splits are manual. Shorting, leverage and automatic order placement are not supported.</p></div></section></div>`;}
function render(){renderCount++;charts={};researchMemo.clear();$('#mode').value=mode;$('#crumb').textContent=TITLES[page];document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#source-banner').className='source-banner '+(mode==='real'?'real':'');$('#source-banner').textContent=mode==='demo'?'◉  DEMO WORKSPACE — all prices, trades and returns are synthetic examples. Your real portfolio is separate.':'NSE equities · Daily closing prices · Private workspace';
try{$('#main').innerHTML=(settingsError?`<div class="callout error">${h(settingsError)}</div>`:'')+({overview:scannerHome,research:researchBrief,learning:learningPage,backtest:backtestPage,portfolio:portfolioPage,data:dataPage}[page])();}catch(e){$('#main').innerHTML=`<div class="callout error"><h2>We could not read this workspace</h2><p>${h(e.message)}</p><p>Saved data has not been replaced. Export the original browser data before attempting recovery.</p><button data-action="raw-backup">Export original workspace data</button><button data-page="data">Open data settings</button></div>`;}
}
async function cacheOpen(){return new Promise((resolve,reject)=>{const request=indexedDB.open('niftylab-market-v2',1);request.onupgradeneeded=()=>request.result.createObjectStore('prices',{keyPath:'symbol'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function cacheLoad(){db=await cacheOpen();return new Promise((resolve,reject)=>{const req=db.transaction('prices').objectStore('prices').getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function cacheSave(d){if(!db){cacheError='Market history is available in this tab only; persistent price storage is unavailable. Export imported CSVs before closing.';return;}return new Promise((resolve,reject)=>{const tx=db.transaction('prices','readwrite');tx.objectStore('prices').put(d);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
async function refresh(){if(busy)return;if(mode==='demo'){render();notify('Demo recalculated. Synthetic history is unchanged.');return;}if(location.protocol==='file:'){notify('Fetching needs the local server. Run python3 server.py, or import CSVs.');page='data';render();return;}
busy=true;marketErrors=[];render();let holdings=[];try{holdings=Object.keys(positionBook().holdings);}catch{}const list=[...new Set(['NIFTYBEES',selected,...holdings,...watch])];
for(let i=0;i<list.length;i+=3){await Promise.all(list.slice(i,i+3).map(async s=>{try{const response=await fetch('/api/history?symbol='+encodeURIComponent(s),{signal:AbortSignal.timeout(25000)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Request failed.');payload.bars=C.validateBars(payload.bars);dataCache[s]=payload;try{await cacheSave(payload);}catch{cacheError='Some fetched history could not be saved for reuse. Portfolio data is unaffected.';}}catch(e){marketErrors.push(s+': '+e.message);}}));}
busy=false;render();notify(marketErrors.length?'Fetch finished with errors. Existing datasets were retained.':'Daily history updated.');}
function download(name,text,type='application/json'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportLedger(){download(`nifty-lab-${mode}-backup.json`,JSON.stringify({version:2,mode,transactions:read('ledger',[]),notes:read('notes',{}),snapshots:read('snapshots',[]),openingHoldings:openingHoldings()},null,2));}
function persistRows(rows,changedDate){C.ledger(rows);write('ledger',rows);const snapshots=read('snapshots',[]).filter(s=>s.date<changedDate);write('snapshots',snapshots);}
function openTransaction(){const form=$('#transaction-form');form.reset();form.elements.date.value=C.today();form.elements.date.max=C.today();form.elements.symbol.value=selected;$('#transaction-error').textContent='';$('#transaction-mode').textContent=mode==='demo'?'Demo ledger — synthetic practice only.':'Your real ledger — enter actual funding and trades.';updateTransaction();$('#transaction-dialog').showModal();}
function updateTransaction(){const f=$('#transaction-form'),kind=f.elements.kind.value,trade=['BUY','SELL'].includes(kind),split=kind==='SPLIT';f.elements.symbol.disabled=!(trade||split);f.elements.symbol.required=trade||split;f.elements.quantity.disabled=!(trade||split);f.elements.price.disabled=split;f.elements.fees.disabled=!trade;$('#quantity-label').firstChild.textContent=split?'New shares per old share':'Quantity';$('#price-label').firstChild.textContent=trade?'Price per share (₹)':'Amount (₹)';$('#transaction-help').textContent=split?'For 2-for-1 enter 2. For 1-for-2 enter 0.5. Cost basis is preserved.':trade?'Enter the original execution price and total fees. Record a deposit before a purchase.':'Enter cash actually deposited, withdrawn, or received as a dividend.';}
function showSize(form){try{const d=analyze(selected),b=d.at(-1),p=portfolioState();C.assert(!p.missing.length,'Recent prices are missing for '+p.missing.join(', '));C.assert(mode==='demo'||!C.stale(d),'Refresh stale prices before sizing.');if(!b.signal){$('#size-result').innerHTML='<div class="size-result"><strong>0 shares</strong><p>The baseline conditions do not all pass. Review the failed conditions.</p></div>';return;}C.assert(p.value.equity>0,'Record a funding deposit first.');const result=C.size({equity:p.value.equity,cash:p.book.cash,price:b.rawClose,stop:Number(form.get('stop')),existing:(p.book.holdings[selected]?.quantity||0)*b.rawClose,risk:Number(form.get('risk'))/100,cap:Number(form.get('cap'))/100,bps});$('#size-result').innerHTML=`<div class="size-result"><strong>${result.quantity} shares</strong><p>${mode==='demo'?'Demo scenario':'Hypothetical additional purchase'} · limited by ${h(result.binding)}</p><div class="stat-pair"><div class="mini-stat"><small>Cash required</small><b>${money(result.cost)}</b></div><div class="mini-stat"><small>Planned loss</small><b>${money(result.loss)}</b></div></div>${Object.entries(result.limits).map(([k,v])=>`<div class="list-row"><span>${k}</span><b>${v} shares</b></div>`).join('')}</div>`;}catch(e){$('#size-result').innerHTML=`<div class="callout error">${h(e.message)}</div>`;}}
let pendingRestore=null;
async function handleForm(e){const form=e.target;if(['quick-research','scan-search','scan-budget','opening-holdings'].includes(form.id))return;e.preventDefault();const f=new FormData(form);try{
if(form.id==='transaction-form'){const kind=f.get('kind'),trade=['BUY','SELL'].includes(kind),split=kind==='SPLIT';const row={id:uid(),date:f.get('date'),kind,symbol:trade||split?C.symbol(f.get('symbol')):'',quantity:trade||split?Number(f.get('quantity')):0,price:split?0:Number(f.get('price')),fees:trade?Number(f.get('fees')):0};persistRows([...read('ledger',[]),row],row.date);$('#transaction-dialog').close();render();notify('Transaction saved.');}
else if(form.id==='size-form')showSize(f);
else if(form.id==='watch-form'){const next=[...new Set(String(f.get('symbols')).split(',').filter(s=>s.trim()).map(C.symbol))];C.assert(next.length>0&&next.length<=20,'Enter 1–20 symbols.');localStorage.setItem('niftylab-watch',JSON.stringify(next));watch=next;if(!watch.includes(selected))selected=watch[0];render();notify('Watchlist updated.');}
else if(form.id==='backtest-form'){const value=Number(f.get('bps'));C.backtest(analyze(selected),f.get('start'),value);write('backtest-start',f.get('start'));localStorage.setItem('niftylab-cost',String(value));bps=value;render();notify('Evaluation updated.');}
else if(form.id==='journal-form'){const notes=read('notes',{});notes[selected]=String(f.get('note')).slice(0,5000);write('notes',notes);notify('Research note saved.');}
else if(form.id==='price-import'){C.assert(mode==='real','Use the real workspace to import history.');const file=f.get('file');C.assert(file.size>0&&file.size<=8e6,'Select a CSV smaller than 8 MB.');const s=C.symbol(f.get('symbol')),bars=C.pricesCSV(await file.text()),payload={symbol:s,source:'Imported CSV: '+file.name,bars,fetchedAt:new Date().toISOString()};await cacheSave(payload);dataCache[s]=payload;render();notify(s+' history imported.');}
else if(form.id==='ledger-import'){const file=f.get('file');C.assert(file.size>0&&file.size<5e6,'Select a JSON backup smaller than 5 MB.');const value=JSON.parse(await file.text());if(value.mode)C.assert(value.mode===mode,'This backup belongs to the '+value.mode+' workspace. Switch workspaces first.');const rows=Array.isArray(value)?value:value.transactions;C.assert(Array.isArray(rows),'No transaction list found.');const converted=rows.map(r=>({id:uid(),date:r.date,kind:r.kind,symbol:r.symbol?C.symbol(r.symbol):'',quantity:C.number(r.quantity),price:C.number(r.price),fees:C.number(r.fees)}));const book=C.ledger(converted);let notes={};if(value.notes){C.assert(typeof value.notes==='object'&&!Array.isArray(value.notes),'Invalid research notes.');for(const [s,n] of Object.entries(value.notes)){C.assert(typeof n==='string'&&n.length<=5000,'Invalid note.');notes[C.symbol(s)]=n;}}
pendingRestore={rows:converted,notes,mode};$('#restore-preview').innerHTML=`<div class="callout"><b>Validated ${converted.length} transactions.</b><p>Cash: ${money(book.cash)} · ${Object.keys(book.holdings).length} open holdings.</p><p>This replaces the ${h(mode)} ledger and research notes. Snapshots are cleared because marks cannot be reverified.</p><button type="button" class="primary small" data-action="restore">Replace ledger with this backup</button></div>`;}
}catch(err){if(form.id==='transaction-form')$('#transaction-error').textContent=err.message;else notify(err.message);}}
document.addEventListener('submit',handleForm);
document.addEventListener('change',e=>{try{if(e.target.id==='mode'){mode=e.target.value;pendingRestore=null;localStorage.setItem('niftylab-mode',mode);render();}else if(e.target.id==='stock-selector'){selected=C.symbol(e.target.value);render();}else if(e.target.id==='period'){period=Number(e.target.value);render();}else if(e.target.id==='watch-filter'){filter=e.target.value;render();}else if(e.target.id==='transaction-kind')updateTransaction();}catch(err){notify(err.message);}});
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-page]');if(!b)return;try{if(b.dataset.page){page=b.dataset.page;history.replaceState(null,'','#'+page);render();window.scrollTo(0,0);return;}if(b.dataset.stock){selected=C.symbol(b.dataset.stock);page='research';render();window.scrollTo(0,0);return;}
if(b.dataset.delete){const old=read('ledger',[]),r=old.find(x=>x.id===b.dataset.delete);if(r&&confirm(`Delete ${r.kind} on ${r.date}? Later transactions must remain valid.`)){persistRows(old.filter(x=>x.id!==r.id),r.date);render();notify('Transaction deleted.');}return;}
if(b.dataset.exportPrice){const d=dataCache[b.dataset.exportPrice];download(b.dataset.exportPrice+'.csv',priceExport(d.bars),'text/csv');return;}
switch(b.dataset.action){case'refresh':await refresh();break;case'transaction':openTransaction();break;case'close-dialog':$('#transaction-dialog').close();break;case'export-ledger':exportLedger();break;
case'raw-backup':{const values={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k.startsWith('niftylab'))values[k]=localStorage.getItem(k);}download('nifty-lab-recovery.json',JSON.stringify(values,null,2));break;}
case'snapshot':{const p=portfolioState();C.assert(p.value,'Load all holding prices first.');const snapshots=read('snapshots',[]).filter(s=>s.date!==C.today());snapshots.push({date:C.today(),equity:p.value.equity,profit:p.value.profit,net:p.book.net,priceDates:p.dates});write('snapshots',snapshots.sort((a,b)=>a.date.localeCompare(b.date)));render();notify('Review snapshot saved with current mark dates.');break;}
case'restore':{C.assert(pendingRestore?.mode===mode,'Revalidate the backup in this workspace.');if(confirm('Replace the current ledger and research notes? Export your current backup first if needed.')){const original={transactions:read('ledger',[]),notes:read('notes',{}),snapshots:read('snapshots',[])};write('pre-restore-backup',original);write('ledger',pendingRestore.rows);write('notes',pendingRestore.notes);write('snapshots',[]);pendingRestore=null;render();notify('Backup restored. Previous state is retained in browser recovery data.');}break;}
case'export-backtest':{const d=analyze(selected),start=read('backtest-start',null)||d[Math.max(200,d.length-504)].date;const r=C.backtest(d,start,bps);download(selected+'-evaluation.csv','Date,Strategy,NIFTYBEES\n'+r.points.map(p=>[p.date,p.strategy,p.benchmark].join(',')).join('\n'),'text/csv');break;}
case'price-template':download('price-format-example.csv','Date,Open,High,Low,Close,Adj Close,Volume\n2024-01-02,100,103,99,102,102,100000\n2024-01-03,102,104,101,103,103,110000\n','text/csv');break;
}}catch(err){notify(err.message);}});
function priceExport(bars){return 'Date,Open,High,Low,Close,Adj Close,Volume\n'+bars.map(b=>{const factor=b.rawClose/b.close;return [b.date,b.open*factor,b.high*factor,b.low*factor,b.rawClose,b.close,b.volume].join(',');}).join('\n');}
document.addEventListener('pointermove',e=>{const box=e.target.closest('[data-chart]');if(!box)return;const chart=charts[box.dataset.chart];if(!chart)return;const rect=box.getBoundingClientRect(),i=Math.max(0,Math.min(chart.points.length-1,Math.round(((e.clientX-rect.left)/rect.width*chart.width-46)/(chart.width-58)*(chart.points.length-1))));const p=chart.points[i],tip=box.querySelector('.chart-tooltip');tip.hidden=false;tip.textContent=p.date+' · '+chart.keys.map((k,j)=>chart.labels[j]+': '+p[k].toFixed(2)).join(' / ');});
document.addEventListener('pointerout',e=>{const box=e.target.closest('[data-chart]');if(box&&!box.contains(e.relatedTarget))box.querySelector('.chart-tooltip').hidden=true;});
window.addEventListener('storage',e=>{if(e.key?.startsWith('niftylab')){notify('Workspace changed in another tab. View refreshed.');render();}});
window.addEventListener('DOMContentLoaded',async function init(){try{mode='real';for(const [key,value] of Object.entries(window.NIFTY_DATA||{})){dataCache[key]={...value,bars:C.validateBars(value.bars)};}const saved=JSON.parse(localStorage.getItem('niftylab-watch')||'null');if(saved){C.assert(Array.isArray(saved)&&saved.length>0&&saved.length<=20,'Invalid saved watchlist.');watch=saved.map(C.symbol);}const c=localStorage.getItem('niftylab-cost');if(c!==null){C.assert(Number(c)>=0&&Number(c)<=1000&&Number.isFinite(Number(c)),'Invalid saved costs.');bps=Number(c);}}catch(e){settingsError='Browser storage could not be read: '+e.message+' Export recovery data before clearing storage.';}
const hash=location.hash.slice(1);if(TITLES[hash])page=hash;render();try{const saved=await cacheLoad();for(const d of saved){try{dataCache[C.symbol(d.symbol)]={...d,bars:C.validateBars(d.bars)};}catch{cacheError='A saved price dataset was invalid and was not used. Reimport the original CSV.';}}}catch{cacheError='Persistent price storage is unavailable. Imported history lasts only in this tab; export source CSVs before closing.';}render();});

function portfolioPage(){return heading('YOUR ACCOUNT','My portfolio','Opening holdings and recorded trades', '<button class="primary" data-action="transaction">Record transaction</button>')+holdingPanel()+'<details class="quiet-details"><summary>Detailed transaction ledger & performance</summary>'+ledgerPortfolioPage()+'</details>';}
