const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function context(rows,holdings,budget){const box={window:{NIFTY_SCAN:{rows}},localStorage:{getItem:()=>null},document:{addEventListener(){}},read:()=>budget,Date,Math,Number,JSON,Set,Object,Array,console};box.window.addEventListener=()=>{};vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(__dirname,'../scanner-ui.js'),'utf8'),box);box.currentHoldings=()=>holdings;return box;}
const row=(s,score=90)=>({symbol:s,combined:score,entry:true,date:new Date().toISOString().slice(0,10),price:100,stopFraction:.05});
test('basket shares cash once and caps every position',()=>{const c=context(Array.from({length:20},(_,i)=>row('S'+i,90-i)),[],10000);const p=vm.runInContext('scanAllocation()',c),a=Object.values(p);assert(a.reduce((s,p)=>s+p.cost,0)<=10000);assert(a.every(p=>p.cost<=1000));assert(a.reduce((s,p)=>s+p.loss,0)<=200);});
test('existing overweight holding gets zero additional shares',()=>{const c=context([row('HELD'),row('NEW')],[{symbol:'HELD',value:20000,estimated:false}],10000);const p=vm.runInContext('scanAllocation()',c);assert(!p.HELD);assert(p.NEW);});
test('old estimated holdings block sizing until updated',()=>{const c=context([row('NEW')],[{symbol:'HELD',value:20000,estimated:true,asOf:'2020-01-01'}],10000);assert.equal(Object.keys(vm.runInContext('scanAllocation()',c)).length,0);});
test('unpriced holding blocks basket and stale entries are ignored',()=>{const c=context([row('NEW')],[{symbol:'HELD',value:null,estimated:false}],10000);assert.equal(Object.keys(vm.runInContext('scanAllocation()',c)).length,0);const d=context([{...row('OLD'),date:'2020-01-01'}],[],10000);assert.equal(Object.keys(vm.runInContext('scanAllocation()',d)).length,0);});
test('short-term priority ranks by short score, not combined, and takes two',()=>{const c=context([{...row('LONG',99),short:70,eligible:true},{...row('SHORT',75),short:95,eligible:true},{...row('SECOND',85),short:85,eligible:true}],[],0);const picks=vm.runInContext('shortTermCandidates().map(r=>r.symbol)',c);assert.deepEqual(Array.from(picks),['SHORT','SECOND']);});
test('short-term priorities exclude nonentries, stale, failed or illiquid rows',()=>{const c=context([{...row('WATCH'),short:99,eligible:true,entry:false},{...row('OLD'),short:99,eligible:true,date:'2020-01-01'},{...row('FAIL'),short:99,eligible:true,refreshError:'failed'},{...row('THIN'),short:99,eligible:false}],[],0);assert.equal(vm.runInContext('shortTermCandidates().length',c),0);});
