/* Public-source startup and learning UI. No private portfolio or bundled data needed. */
const {chromium}=require((process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||'')?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const {spawn}=require('node:child_process'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),port=8879;const server=spawn('python3',['server.py','--no-scan','--port',String(port)],{cwd:root,stdio:['ignore','pipe','pipe']});let browser;
try{await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Server startup timeout')),10000);server.stdout.on('data',x=>{if(x.toString().includes('Open http')){clearTimeout(t);resolve()}});server.on('exit',()=>reject(Error('Server exited')))});
browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const page=await browser.newPage({baseURL:'http://127.0.0.1:'+port,viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.waitForSelector('.learning-teaser');assert.match(await page.locator('main').innerText(),/Is the model getting better/);
for(const name of ['market-data.js','scan-seed.js','portfolio-seed.js'])assert.equal((await page.request.get('/'+name)).status(),200);
const r=await page.request.get('/api/scan'),status=await r.json(),small=await (await page.request.get('/api/scan?since='+status.version)).json();assert.equal(small.unchanged,true);assert(!small.rows);
await page.locator('nav [data-page=learning]').click();await page.waitForSelector('.learning-metrics');assert.match(await page.locator('main').innerText(),/Average forecast error/);assert.match(await page.locator('main').innerText(),/historical training examples, excluded from forward accuracy/);
// Controlled fixture verifies populated forecast cards without fabricating production records.
const predictions=[5,21].map(horizon=>({horizon,predicted:0.015,training_n:40,band:null,issued_at:'2026-09-21T10:00:00+05:30',asof_date:'2026-09-18'}));
if(predictions.length){await page.evaluate(predictions=>{scanData.rows=[{symbol:'INFY',name:'Infosys',date:predictions[0].asof_date,long:60,short:55,combined:58,reasons:[],longParts:{Trend:60},shortParts:{Volume:55},forecast:{predictions},coverage:'Test UI fixture'}];openScore('INFY');},predictions);await page.waitForSelector('.forecast-grid');assert.match(await page.locator('#score-dialog').innerText(),/Recorded return forecasts/);await page.locator('[data-learning=log]').click();await page.waitForSelector('.learning-metrics');}
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS public-source startup, empty seed stubs, lightweight polling, learning history, populated forecast cards, mobile, no page errors');
}finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
