/* Public-source startup and learning UI. No private portfolio or bundled data needed. */
const {chromium}=require((process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||'')?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const {spawn}=require('node:child_process'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),port=8879;const server=spawn('python3',['server.py','--no-scan','--port',String(port)],{cwd:root,stdio:['ignore','pipe','pipe']});let browser;
try{await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Server startup timeout')),10000);server.stdout.on('data',x=>{if(x.toString().includes('Open http')){clearTimeout(t);resolve()}});server.on('exit',()=>reject(Error('Server exited')))});
browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});const page=await browser.newPage({baseURL:'http://127.0.0.1:'+port,viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.waitForSelector('.learning-teaser');assert.match(await page.locator('main').innerText(),/Is the model getting better/);
await page.evaluate(()=>{localStorage.setItem(snapshotKey,JSON.stringify([{symbol:'COALINDIA',reportedValue:30743,cost:32520,quantity:null,asOf:'2026-09-20'}]));render();});
assert.match(await page.locator('main').innerText(),/Fixed reported value/);
await page.getByRole('button',{name:'Set share quantities'}).click();
await page.locator('[name=qty0]').fill('90');await page.getByRole('button',{name:'Save holdings',exact:true}).click();
await page.evaluate(()=>{quoteState={quotes:{COALINDIA:{price:450,previousClose:440,change:10,quoteTime:new Date().toISOString()}},errors:{}};render();});
assert.equal(await page.evaluate(()=>currentHoldings()[0].dayChange),900);
assert.equal(await page.evaluate(()=>currentHoldings()[0].value),40500);
await page.locator('nav [data-page=research]').click();
assert.match(await page.locator('main').innerText(),/Choose a company/);
assert.equal(await page.locator('#quick-research').count(),1);
await page.locator('nav [data-page=data]').click();assert.equal(await page.locator('#watch-form').count(),0);
await page.locator('nav [data-page=overview]').click();
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS exact share setup, daily P&L, quote valuation, research chooser, no watchlist textbox, mobile, no page errors');
}finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
